"""Compile the final SysML extension with the shared KerML grammar compiler.

The maintained EBNF preserves the strict published alternatives. Original rule
actions, printed page anchors and undefined nonterminals are separately pinned.
This command does not acquire standards or apply corpus compatibility changes.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tools/kerml-grammar'))
from generate import format_rust, runtime_grammar, tables
from inventory import Grammar


def grammar_source():
    manifest = json.loads((ROOT / 'standards/grammar/sysml-2.0-source.json').read_text(encoding='utf-8'))
    authority = manifest['authority']
    assert hashlib.sha256((ROOT / authority['path']).read_bytes()).hexdigest() == authority['sha256'], 'SysML PDF identity changed'
    kerml = (ROOT / 'standards/grammar/kerml-1.0.ebnf').read_text(encoding='utf-8')
    sysml = (ROOT / 'standards/grammar/sysml-2.0.ebnf').read_text(encoding='utf-8')
    pattern = r'^([A-Za-z_][A-Za-z_0-9]*)\s*=\s*(.*);$'
    base = dict(re.findall(pattern, kerml, re.M))
    overrides = dict(re.findall(pattern, sysml, re.M))
    assert overrides == {r['name']: r['recognition_rhs'] for r in manifest['rules']}, 'SysML EBNF/source anchors differ'
    base.update(overrides)
    combined = '\n'.join(f'{name} = {rhs};' for name, rhs in base.items())
    grammar = Grammar(combined, unresolved=manifest['undefined_nonterminals'])
    grammar.keywords = set(manifest['reserved_keywords'])
    grammar, kinds = runtime_grammar(grammar)
    for name in manifest['undefined_nonterminals']:
        grammar.by_name[name] = []
    return grammar, kinds


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    options = parser.parse_args()
    grammar, kinds = grammar_source()
    output = ['// @generated by tools/sysml-grammar/generate.py; do not edit.',
              '// Final SysML 2.0 overrides; shared lexer, arena and KerML precedence.',
              'use super::{Production, Rule, Symbol};']
    data = format_rust(output + tables(grammar, kinds))
    path = ROOT / 'crates/kerml-syntax/src/production/generated_sysml.rs'
    if options.write:
        path.write_bytes(data)
    else:
        assert path.read_bytes().replace(b'\r\n', b'\n') == data, 'stale SysML grammar tables'
    print(f'{len(set(kinds.values()))} named productions; {len(grammar.rules)} grammar alternatives; SysML tables current')


if __name__ == '__main__':
    main()
