"""Compile the final SysML extension with the shared KerML grammar compiler.

The maintained EBNF preserves the strict published alternatives. Original rule
actions, printed page anchors and undefined nonterminals are separately pinned.
Operational v1 applies only the exact independently pinned compatibility diff.
This command does not acquire standards or rewrite the published grammar.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tools/kerml-grammar'))
from generate import format_rust, runtime_grammar, tables
from inventory import Grammar


COMPATIBILITY = ROOT / 'standards/grammar/sysml-2.0-operational-v1.json'


def operational_overrides(overrides):
    """Fail closed if either side of the authorized EBNF diff drifts."""
    compatibility = json.loads(COMPATIBILITY.read_text(encoding='utf-8'))
    published = compatibility['published_grammar']
    source = (ROOT / published['path']).read_bytes().replace(b'\r\n', b'\n')
    assert hashlib.sha256(source).hexdigest() == published['sha256'], 'Published SysML grammar identity changed'
    assert len(compatibility['changes']) == 5
    assert len({change['decision'] for change in compatibility['changes']}) == 4
    result = dict(overrides)
    for change in compatibility['changes']:
        name = change['production']
        assert result[name] == change['published_rhs'], f'Published {name} differs from reviewed compatibility input'
        result[name] = change['operational_rhs']
    return result


def grammar_source(operational=False):
    manifest = json.loads((ROOT / 'standards/grammar/sysml-2.0-source.json').read_text(encoding='utf-8'))
    authority = manifest['authority']
    assert hashlib.sha256((ROOT / authority['path']).read_bytes()).hexdigest() == authority['sha256'], 'SysML PDF identity changed'
    kerml = (ROOT / 'standards/grammar/kerml-1.0.ebnf').read_text(encoding='utf-8')
    sysml = (ROOT / 'standards/grammar/sysml-2.0.ebnf').read_text(encoding='utf-8')
    pattern = r'^([A-Za-z_][A-Za-z_0-9]*)\s*=\s*(.*);$'
    base = dict(re.findall(pattern, kerml, re.M))
    overrides = dict(re.findall(pattern, sysml, re.M))
    assert overrides == {r['name']: r['recognition_rhs'] for r in manifest['rules']}, 'SysML EBNF/source anchors differ'
    if operational:
        overrides = operational_overrides(overrides)
    base.update(overrides)
    combined = '\n'.join(f'{name} = {rhs};' for name, rhs in base.items())
    grammar = Grammar(combined, unresolved=manifest['undefined_nonterminals'])
    grammar.keywords = set(manifest['reserved_keywords'])
    grammar, kinds = runtime_grammar(grammar)
    for name in manifest['undefined_nonterminals']:
        grammar.by_name[name] = []
    return grammar, kinds


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    options = parser.parse_args()
    for operational in [False, True]:
        grammar, kinds = grammar_source(operational)
        label = 'Operational v1' if operational else 'Published SysML 2.0'
        comment = 'Operational v1' if operational else 'Final SysML 2.0 overrides'
        output = ['// @generated by tools/sysml-grammar/generate.py; do not edit.',
                  f'// {comment}; shared lexer, arena and KerML precedence.',
                  'use super::{Production, Rule, Symbol};']
        if operational:
            digest = hashlib.sha256(COMPATIBILITY.read_bytes().replace(b'\r\n', b'\n')).hexdigest()
            output.append(f'pub(super) const COMPATIBILITY_MANIFEST_SHA256: &str = "{digest}";')
        data = format_rust(output + tables(grammar, kinds))
        filename = 'generated_sysml_operational.rs' if operational else 'generated_sysml.rs'
        path = ROOT / 'crates/kerml-syntax/src/production' / filename
        if options.write:
            path.write_bytes(data)
        else:
            assert path.read_bytes().replace(b'\r\n', b'\n') == data, f'stale {label} grammar tables'
        print(f'{len(set(kinds.values()))} named productions; {len(grammar.rules)} grammar alternatives; {label} tables current')


if __name__ == '__main__':
    main()
